mso/resource_mso_schema_site_anp_epg_domain.go
mso/resource_mso_schema_site_anp_epg_selector.go
mso/resource_mso_schema_site_anp_epg_static_leaf.go
mso/resource_mso_schema_site_anp_epg_static_port.go
mso/resource_mso_schema_site_bd_l3out.go
mso/resource_mso_schema_site_external_epg_selector.go
mso/resource_mso_schema_site_vrf_region_cidr.go
mso/resource_mso_schema_site_vrf_region_cidr_subnet.go
mso/resource_mso_schema_template_anp_epg_contract.go
mso/resource_mso_schema_template_anp_epg_subnet.go
mso/resource_mso_schema_template_bd_subnet.go
mso/resource_mso_schema_template_contract_filter.go
mso/resource_mso_schema_template_external_epg_contract.go
mso/resource_mso_schema_template_external_epg_subnet.go
mso/resource_mso_tenant.go
website/docs/r/tenant.html.markdown

delete method of child resources updated

---

mso/resource_mso_tenant.go

crashing issue solved for on-prem site association

added check for cloud account

---

examples/schema_site/main.tf
examples/schema_site/variable.tf
website/docs/r/schema_site.html.markdown

[mso_schema_site ]Added examples and documentations for multi site associations for same schema template.  solves issue #14

---

go.mod
go.sum
mso/resource_mso_site.go

resolved #40 
- Add function GetSiteViaName() for mso_site resource
- Support mso_site for ND hosted MSO

Support mso_site for ND hosted MSO

---

go.mod
go.sum
mso/datasource_mso_user.go
mso/resource_mso_user.go
vendor/github.com/ciscoecosystem/mso-go-client/client/client.go
vendor/github.com/ciscoecosystem/mso-go-client/client/client_service.go
vendor/github.com/ciscoecosystem/mso-go-client/models/schema_template_externalepg.go
vendor/modules.txt
website/docs/d/user.html.markdown
website/docs/r/user.html.markdown

Made changes w.r.t mso_user to suppot MSO/ND platform

---

mso/datasource_mso_site.go

Add option to accommodate v1 and v2 for mso_site datasource

fix version issue in datasource mso_site

---

mso/resource_mso_schema_template_anp_epg.go
website/docs/r/schema_template_anp_epg.html.markdown

Fix import function where vrf and bd are only required under certain condition

---

examples/schema_template_contract/main.tf
mso/resource_mso_schema_template_contract.go
website/docs/d/schema_template_contract.html.markdown
website/docs/r/schema_template_contract.html.markdown

Made changes to support change of parameter filter_relationship

---

CHANGELOG.md
website/docs/d/schema_template_service_graph.html.markdown
website/docs/d/user.html.markdown
website/docs/r/schema_template_service_graph.html.markdown
website/docs/r/user.html.markdown

Fixed documentation and made changes to CHANGELOG.md file

---

examples/schema_site_vrf_region/main.tf
examples/schema_site_vrf_region_cidr_subnet/main.tf
go.mod
go.sum
mso/datasource_mso_schema_site_vrf_region.go
mso/resource_mso_schema_site_vrf_region.go
mso/resource_mso_schema_site_vrf_region_cidr_subnet.go
vendor/github.com/ciscoecosystem/mso-go-client/client/client_service.go
vendor/github.com/ciscoecosystem/mso-go-client/models/schema_template_externalepg.go
vendor/modules.txt
website/docs/r/schema_site_vrf_region.html.markdown
website/docs/r/schema_site_vrf_region_cidr_subnet.html.markdown

Fix mso_schema destroy issue and mso_schema_site_vrf/mso_schema_site_vrf_region_subnet zone parameter not mandatory

---

website/docs/r/schema_site_bd_subnet.html.markdown
website/docs/r/schema_template_external_epg_subnet.html.markdown
website/docs/r/schema_template_filter_entry.html.markdown

should be /ip/{ip} not /subnet/{ip}

Correcting mistake in import command examples for resource mso_schema_template_external_epg_subnet and mso_schema_site_bd_subnet.

---

examples/schema_template_external_epg_subnet/main.tf
go.mod
go.sum
mso/datasource_mso_schema_template_external_epg_subnet.go
mso/resource_mso_schema_template_external_epg_subnet.go
vendor/github.com/ciscoecosystem/mso-go-client/client/client.go
vendor/github.com/ciscoecosystem/mso-go-client/models/schema_template_anp_epg.go
vendor/github.com/ciscoecosystem/mso-go-client/models/schema_template_externalepg_subnet.go
vendor/modules.txt
website/docs/r/schema_template_external_epg_subnet.html.markdown

Set external epg subnet ip as ForceNew
Set external epg subnet name as empty string in resourceMSOTemplateExtenalepgSubnetImport()
resolve #112

[bugfix] reset schema_template_external_epg_subnet name attr to fix terraform import

---

go.mod
go.sum
mso/resource_mso_schema_template_vrf_contract.go
website/docs/r/schema_template_vrf_contract.html.markdown

[minor_change] import fix with correct example in docs

---

mso/datasource_mso_schema_template_filter_entry.go
mso/resource_mso_schema_template_filter_entry.go

[minor_change] description and tcp_session_rules fix

---

examples/schema_template_bd/main.tf
go.mod
go.sum
mso/datasource_mso_schema_template_bd.go
mso/resource_mso_schema_template_bd.go
vendor/github.com/ciscoecosystem/mso-go-client/models/model.go
vendor/github.com/ciscoecosystem/mso-go-client/models/schema_template_bd.go
vendor/modules.txt
website/docs/d/schema_template_bd.html.markdown
website/docs/r/schema_template_bd.html.markdown

[minor_change] support for dhcpLabels

---

examples/schema_template_vrf/main.tf
go.mod
go.sum
mso/datasource_mso_schema_template_vrf.go
mso/resource_mso_schema_template_vrf.go
vendor/github.com/ciscoecosystem/mso-go-client/models/schema_site_anp_epg_domain.go
vendor/github.com/ciscoecosystem/mso-go-client/models/schema_template_vrf.go
vendor/modules.txt
website/docs/d/schema_template_vrf.html.markdown
website/docs/r/schema_template_vrf.html.markdown

Added ip_data_plane_learning and preferred_group arguments to schema_template_vrf resource

[minor_changes] Added additional arguments to schema_template_vrf resource.

---

mso/resource_mso_schema.go
mso/util.go

Note:
Fixed mso_schema read issue during the state file refresh when the object is not present in the MSO/NDO but present in the state file.

Fixed mso_schema read issue during the state file refresh

---

examples/schema_template_anp_epg/main.tf
examples/schema_template_bd/main.tf
go.mod
go.sum
mso/datasource_mso_schema_template_anp_epg.go
mso/datasource_mso_schema_template_bd.go
mso/resource_mso_schema_template_anp_epg.go
mso/resource_mso_schema_template_bd.go
vendor/github.com/ciscoecosystem/mso-go-client/models/schema_site_bd.go
vendor/github.com/ciscoecosystem/mso-go-client/models/schema_site_vrf_region_route_leak.go
vendor/github.com/ciscoecosystem/mso-go-client/models/schema_template_anp_epg.go
vendor/github.com/ciscoecosystem/mso-go-client/models/schema_template_bd.go
vendor/modules.txt
website/docs/d/schema_template_anp_epg.html.markdown
website/docs/d/schema_template_bd.html.markdown
website/docs/r/schema_template_anp_epg.html.markdown
website/docs/r/schema_template_bd.html.markdown

Note:
Added description attribute to schema_template_bd and schema_template_anp_epg resources and updated resource examples and documents.

Added description attribute to schema_template_bd and schema_template_anp_epg resources

---

go.mod
go.sum
mso/resource_mso_schema_template_bd.go
vendor/github.com/ciscoecosystem/mso-go-client/client/client_service.go
vendor/github.com/ciscoecosystem/mso-go-client/client/template_service.go
vendor/modules.txt

Note:
Added version check to handle the latest NDO dhcp polices issue.

Fixed DHCP Policies issue on latest NDO

---

examples/system_config/main.tf
go.mod
go.sum
mso/datasource_mso_system_config.go
mso/provider.go
mso/resource_mso_system_config.go
vendor/github.com/ciscoecosystem/mso-go-client/models/schema_template_contract.go
vendor/github.com/ciscoecosystem/mso-go-client/models/system_config.go
vendor/modules.txt
website/docs/d/system_config.html.markdown
website/docs/r/system_config.html.markdown

[minor_change] add resource and datasource for system_config

---

examples/schema_template_contract_filter/main.tf
go.mod
go.sum
mso/datasource_mso_schema_template_contract_filter.go
mso/resource_mso_schema_template_contract.go
mso/resource_mso_schema_template_contract_filter.go
vendor/github.com/ciscoecosystem/mso-go-client/models/model.go
vendor/github.com/ciscoecosystem/mso-go-client/models/schema_template_contract_filter.go
vendor/modules.txt
website/docs/d/schema_template_contract_filter.html.markdown
website/docs/r/schema_template_contract.html.markdown
website/docs/r/schema_template_contract_filter.html.markdown

239 align contract with filter

---

examples/schema_template_contract_service_graph/main.tf
mso/datasource_mso_schema_template_contract_service_graph.go
mso/provider.go
mso/resource_mso_schema_template_contract_service_graph.go
mso/util.go
website/docs/d/schema_template_contract_service_graph.html.markdown
website/docs/r/schema_template_contract_service_graph.html.markdown

Note:
Removed Site Template Contract Service Graph logic from mso_schema_template_contract_service_graph resource. PR belongs to: https://github.com/CiscoDevNet/terraform-provider-mso/issues/190

Removed Site Template Contract Service Graph logic from mso_schema_template_contract_service_graph resource

---

examples/schema_site_anp_epg_domain/main.tf
go.mod
go.sum
mso/datasource_mso_schema_site_anp_epg_domain.go
mso/resource_mso_schema_site_anp_epg_domain.go
vendor/github.com/ciscoecosystem/mso-go-client/models/schema_site_anp_epg_domain.go
vendor/modules.txt
website/docs/d/schema_site_anp_epg_domain.html.markdown
website/docs/r/schema_site_anp_epg_domain.html.markdown

247 mso schema site anp epg domain 4 2 attributes

---

go.mod
go.sum
vendor/github.com/ciscoecosystem/mso-go-client/client/client.go
vendor/modules.txt

Updated TLS version on mso-go-client and updated the changes on mso provider.
solves #264

[bug_fix] Updated TLS version on mso-go-client 

---

mso/resource_mso_schema_template_anp_epg.go
mso/util.go

[bugfix] Fix update and delete of mso_schema_template_anp_epg

---

mso/datasource_mso_site.go
mso/resource_mso_schema_site_bd.go
mso/util.go
mso/utils.go

275 bugfix l3out reference site bd removal

---

mso/resource_mso_schema_template_bd.go

277 bugfix subnet in template bd removal

---

mso/resource_mso_schema_site_service_graph.go

Added additional check to avoid error generation checks only required for cloud service graphs. fixes #273

[minor_changes] Fixes error generation for site service graph.

---

mso/resource_mso_schema_site_anp.go

[bugfix] Fix read and import for mso_schema_site_anp resource to select anp in correct site and template combination (DCNE-210)

---

mso/resource_mso_schema_site.go
website/docs/r/schema_site.html.markdown

[bug_fix] Fix importing for mso_schema_site to support multiple templates in the same schema with the same site (DCNE-203)

---

examples/schema_template_vrf/main.tf
go.mod
go.sum
mso/datasource_mso_schema_template_vrf.go
mso/datasource_mso_schema_template_vrf_test.go
mso/resource_mso_schema_template_vrf.go
mso/resource_mso_schema_template_vrf_test.go
vendor/github.com/ciscoecosystem/mso-go-client/models/schema_template_vrf.go
vendor/modules.txt
website/docs/d/schema_template_vrf.html.markdown
website/docs/r/schema_template_vrf.html.markdown

Add RP to mso_schema_template_vrf resource and datasource (DCNE-293)

---

examples/fabric_policies_vlan_pool/main.tf
mso/datasource_mso_fabric_policies_vlan_pool.go
mso/datasource_mso_fabric_policies_vlan_pool_test.go
mso/provider.go
mso/provider_test.go
mso/resource_mso_fabric_policies_vlan_pool.go
mso/resource_mso_fabric_policies_vlan_pool_test.go
website/docs/d/fabric_policies_vlan_pool.html.markdown
website/docs/r/fabric_policies_vlan_pool.html.markdown

[minor_change] Add Resource and Data source for VLAN Pool under Fabric Policy template (DCNE-395)
